### PR TITLE
Make buildable

### PR DESCRIPTION
**Pull request by chadmiller**
Many discrete patches to fix the last 25 years of changes in C and fix a few dozen actual problems in dikumud.

### CODE REVIEW

**Comment by Seifert69** [comment]
Hey Chad, thanks! I'll review and merge this week. Looks great!

If you're interested in helping out in working on Diku III and have made it
with websockets and it outputs HTML rather than pure text.

Not sure how to send you an email and not sure where this ends up :))

Best, Michael

**Comment by Seifert69** [comment]
> Many discrete patches to fix the last 25 years of changes in C and fix a few dozen actual problems in dikumud.

Thanks Chad, I'll review and commit this week. Looks great. If you want to help out on Diku III drop me an email :)

**Comment by chadmiller** [comment]
Beware, there are some changes that change the on-disk format for the player db, like modern crypt accepting longer passwords and storing the hash as more than 16 bytes (or whatever it was in 1990).

**Review by Seifert69 — APPROVED** [review]
It would be best if log was renmaed to slog since that's the name used in Diku II and III

**Review by Seifert69 — APPROVED** [review]

**Review by Seifert69 — APPROVED** [review]

**Review by Seifert69 — APPROVED** [review]

**Review by Seifert69 — APPROVED** [review]

**Pull request merged**
